apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: coin
  labels:
    app: coin
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: coin
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90
  # - type: Pods
  #   pods:
  #     metricName: http_request_duration_milliseconds
  #     targetAverageValue: 300
